repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: df25ab1ba8b2d70333ec8f447ad66cef519a654f
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/hakancelik96/unimport
    rev: 07de9fc2900f077f26b4e0167075bd825f0cf45f
    hooks:
      - id: unimport
        args: [--remove, --include-star-import]
  - repo: https://github.com/pycqa/isort
    rev: 44e3b5d179da5033ce23f796b014e74f3a3259cd
    hooks:
      - id: isort
        files: gdsfactory/.*
        args: [--profile, black, --filter-files]

  - repo: https://github.com/psf/black
    rev: 092959ff1f9253347b01eeb2d6d72e15bad7e25a
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: f35c84dee38f029473d780e029cf5a49933a33e0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.9b0]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 21d3c70d676007470908d39b73f0521d39b3b997
    hooks:
      - id: flake8
  - repo: https://github.com/kynan/nbstripout
    rev: 3843f5f7c586fa6f0df81423f35d52e6af8e3039
    hooks:
      - id: nbstripout
        files: .ipynb
  # - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  #   rev: 6565d773ca281682d7062d4c0be74538cc474cc9
  #   hooks:
  #     - id: pretty-format-java
  #       args: [--autofix]
  #     - id: pretty-format-kotlin
  #       args: [--autofix]
  #     - id: pretty-format-yaml
  #       args: [--autofix, --indent, "2"]

  # - repo: https://github.com/adrienverge/yamllint.git
  #   rev: v1.21.0 # or higher tag
  #   hooks:
  #       - id: yamllint
  #         args: [--format, parsable, --strict]

  # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  #   rev: 0.1.0 # or specific tag
  #   hooks:
  #       - id: yamlfmt

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "214c33306afe17f1cc7d2d55e4da705b6ebe0627"
  #   hooks:
  #     - id: mypy
  #       exclude: ^(docs/|example-plugin/|tests/fixtures)
  #       additional_dependencies:
  #         - "pydantic"

  # - repo: https://github.com/terrencepreilly/darglint
  #   rev: master
  #   hooks:
  #       - id: darglint
  #
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: ""
  #   hooks:
  #       - id: pydocstyle
  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: 2b2f0c74acdb3de316e23ceb7dd0d7945c354050
  #   hooks:
  #     - id: reorder-python-imports
